/*
	Sahara El Beydar
	Credits: ChimpanG, Deliverator
*/

-----------------------------------------------
-- Effects for Natural Wonders
-- Effect: Owned Floodplains do not diminish the appeal of adjacent tiles for any Civilization that owns at least one of these tiles.
-----------------------------------------------

UPDATE	Features
SET		Description = 'LOC_TM_FEATURE_SAHARA_EL_BEYDAR_DESCRIPTION'
WHERE	FeatureType = 'FEATURE_WHITEDESERT';

	UPDATE	Features
	SET		Description = 'LOC_TM_FEATURE_SAHARA_EL_BEYDAR_EFFECT_DESCRIPTION'
	WHERE	FeatureType = 'FEATURE_WHITEDESERT'
	AND EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

	INSERT INTO GameModifiers (ModifierId)
	SELECT	'MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_ATTACH_PLAYERS'
	WHERE EXISTS (SELECT * FROM Features WHERE FeatureType = 'FEATURE_WHITEDESERT')
	AND EXISTS (SELECT * FROM TM_UserSettings WHERE Setting = 'NW_EFFECTS' AND Value = 1);

-----------------------------------------------
-- Modifiers
-----------------------------------------------

INSERT INTO Modifiers
		(ModifierId,														ModifierType,						SubjectRequirementSetId						)
VALUES	('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_ATTACH_FLOODPLAINS_DESERT',	'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_WHITEDESERT'	),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_DESERT',			'MODTYPE_TM_ADJUST_FEATURE_APPEAL',	NULL										),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_ATTACH_FLOODPLAINS_GRASS',	'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_WHITEDESERT'	),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_GRASS',			'MODTYPE_TM_ADJUST_FEATURE_APPEAL',	NULL										),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_ATTACH_FLOODPLAINS_PLAINS',	'MODTYPE_TM_ATTACH_ALL_PLAYERS',	'REQSET_TM_PLAYER_HAS_FEATURE_WHITEDESERT'	),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_PLAINS',			'MODTYPE_TM_ADJUST_FEATURE_APPEAL',	NULL										);

-----------------------------------------------
-- ModifierArguments
-----------------------------------------------

INSERT INTO ModifierArguments
		(ModifierId,														Name,			Value														)
VALUES	('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_ATTACH_FLOODPLAINS_DESERT',	'ModifierId',	'MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_DESERT'	),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_DESERT',			'FeatureType',	'FEATURE_FLOODPLAINS'										),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_DESERT',			'Amount',		1															),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_ATTACH_FLOODPLAINS_GRASS',	'ModifierId',	'MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_GRASS'	),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_GRASS',			'FeatureType',	'FEATURE_FLOODPLAINS_GRASSLAND'								),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_GRASS',			'Amount',		1															),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_ATTACH_FLOODPLAINS_PLAINS',	'ModifierId',	'MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_PLAINS'	),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_PLAINS',			'FeatureType',	'FEATURE_FLOODPLAINS_PLAINS'								),
		('MODIFIER_TM_FEATURE_SAHARA_EL_BEYDAR_FLOODPLAINS_PLAINS',			'Amount',		1															);